language: objective-c
osx_image: xcode7
before_install:
 - gem install cocoapods -v '0.38.2'
 - pod install

script:
 - xcodebuild
 - workspace stopWatch/StopWatch.xcworkspace
 - scheme StopWatch
 - sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
 - destination 'platform=iOS Simulator,name=iPhone,OS=7.0' test
