language: objective-c
osx_image: xcode7

before_install:
 - gem install xcpretty
 - gem install cocoapods -v '0.38.2'
 - pod install
 - brew update
 - brew uninstall xctool
 - brew install xctool

before_script:
 - set -o pipefail

xcode_workspace: StopWatch.xcworkspace
xcode_scheme: StopWatch
xcode_sdk: iphonesimulator